wandb_version: 1

block_size:
  desc: null
  value: 256
emb_dim:
  desc: null
  value: 384
num_layers:
  desc: null
  value: 6
num_heads:
  desc: null
  value: 6
dropout:
  desc: null
  value: 0.2
_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711731679.0
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.11.8
      5: 0.16.4
      6: 4.38.2
      8:
      - 4
      - 5
      13: darwin-arm64
