wandb_version: 1

block_size:
  desc: null
  value: 256
emb_dim:
  desc: null
  value: 384
num_layers:
  desc: null
  value: 6
num_heads:
  desc: null
  value: 6
dropout:
  desc: null
  value: 0.2
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711816424.0
    t:
      1:
      - 1
      - 55
      - 71
      2:
      - 1
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
